name: CI Demo

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - uses: actions/setup-node@v5

            - name: Install dependencies
              run: yarn

            - name: Run tests
              run: yarn test --coverage --run
